args <- commandArgs(trailingOnly = T)
# args <- c(11,0.1)
args <- as.numeric(args)
comp <- as.integer(args[1]):(as.integer(args[1])+4)
cut_pct <- args[2]
# print('components')
# print(comp)
# print('Causal percentage')
# print(cut_pct)

arrID <- as.numeric(Sys.getenv('SLURM_ARRAY_TASK_ID'))
set.seed(arrID)

# suffix of file name generated by this file
name_suf <- paste('_', comp[1],'_',cut_pct,'_',args[3],'_snp','_',arrID, sep = '')

library(dplyr)
library(magrittr)
library(data.table)
library(OmicsPLS)
library(DescTools)
library(ggplot2)
library(pROC)
library(PO2PLS)
library(GenABEL)
# library(MultiABEL)
# library(lassosum)

# rmsep <- function(summ){
#   sqrt(c(crossprod(summ$res))/length(summ$res))
# }
#######################################################################
# load X
# x <- readRDS(paste('./dat_rep/dat_training_',arrID,'.rds', sep = ''))
x_t <- readRDS(paste('./dat_rep/dat_test_',arrID,'.rds', sep = ''))
# dim(x); dim(x_t)

# For PO2PLS
gene <- readRDS(paste('./dat_rep/GeneData_training_',arrID,'.rds', sep = ''))
# gene %>% dim
gene_t <- readRDS(paste('./dat_rep/GeneData_test_',arrID,'.rds', sep = ''))

PCA_weight <- readRDS(paste('./dat_rep/PCAweight_',arrID,'.rds', sep = ''))

load(file=paste('./fit_dat/dat_yz', name_suf, '.RData', sep = ''))
###############
# Z1
#######################################################################
# performance in training

# O2PLS
fit_o2 <- readRDS(file=paste('./fit_files/fit_o2', name_suf, '.rds', sep = ''))
print('O2PLS: correlation of T with True')
print('cor with T_q')
cor(T_q, fit_o2$Tt)
print('cor with PCA(y)')
cor(prcomp(y_nonoise)$x[1:2000,1:5], fit_o2$Tt)
sumy_o2 <- summary(lm(z1~fit_o2$Tt))
print(sumy_o2)


# O2PLS
fit_o2snp <- readRDS(file=paste('./fit_files/fit_o2snp', name_suf, '.rds', sep = ''))
print('O2PLS SNP: correlation of T with True')
print('cor with T_q')
cor(T_q, fit_o2snp$Tt)
print('cor with PCA(y)')
cor(prcomp(y_nonoise)$x[1:2000,1:5], fit_o2snp$Tt)
sumy_o2snp <- lm(z1~fit_o2snp$Tt) %>% summary
print(sumy_o2snp)


# PO2PLS
fit_p <- readRDS(file=paste('./fit_files/fit_p', name_suf, '.rds', sep = ''))
print('PO2PLS: correlation of T with True')
t_p <- with(fit_p$parameters, (gene - gene%*%Wo%*%t(Wo)) %*% W)
print('cor with T_q')
cor(T_q, t_p)
print('cor with PCA(y)')
cor(prcomp(y_nonoise)$x[1:2000,1:5], t_p)
sumy_p <- lm(z1~t_p) %>% summary
print(sumy_p)

# PO2PLS 10 X-specific
fit_pex <- readRDS(file=paste('./fit_files/fit_pex15', name_suf, '.rds', sep = ''))
print('PO2PLS: correlation of T with True')
t_pex <- with(fit_pex$parameters, (gene - gene%*%Wo%*%t(Wo)) %*% W)
print('cor with T_q')
cor(T_q, t_pex)
print('cor with PCA(y)')
cor(prcomp(y_nonoise)$x[1:2000,1:5], t_pex)
sumy_pex <- lm(z1~t_pex) %>% summary
print(sumy_pex)

# PRS Y
prs <- matrix(NA, 2000, 23)
for(yi in 1:23){
  prs_temp <- read.table(paste('./fit_files/PRS_y', yi, name_suf, '.best', sep = ''), header = T)
  prs_temp <- prs_temp[match(rownames(gene),prs_temp$IID), ]
  if(all.equal(prs_temp$IID, rownames(gene))!=T) stop('prs order mismatch')
  prs[,yi] <- prs_temp$PRS
}
rownames(prs) <- rownames(gene)
# ggcorrplot::ggcorrplot(cor(prs))
# PCA of 23 PRS
prs_pca <- prcomp(prs)
prs_pc <- prs_pca$x[,1:5]
print('PRS: correlation of PRS with True')
print('cor with T_q')
cor(T_q, prs_pc)
print('cor with PCA(y)')
cor(prcomp(y_nonoise)$x[1:2000,1:5], prs_pc)
sumy_prs <- lm(z1~prs_pc) %>% summary
print(sumy_prs)

# PRS Z
prsZ <- read.table(paste('./fit_files/PRS_z1',name_suf, '.best', sep = ''), header = T)
prsZ <- prsZ[match(rownames(gene),prsZ$IID), ]
if(all.equal(prsZ$IID, rownames(gene))!=T) stop('prsZ order mismatch')
prsZ <- prsZ$PRS %>% t %>% t
rownames(prsZ) <- rownames(gene)
# ggcorrplot::ggcorrplot(cor(prs))
# PCA of 23 PRS
sumy_prsZ <- lm(z1~prsZ) %>% summary
print(sumy_prsZ)

##################################
# binary
lmfit_o2 <- glm(z1_bi~fit_o2$Tt, family = 'binomial')
sumy_bi_o2 <- lmfit_o2 %>% summary
prob=predict(lmfit_o2,type=c("response"))
# print('AUC of O2PLS in test')
auc_o2 <- roc(z1_bi ~ prob)$auc
print(sumy_bi_o2)

lmfit_o2snp <- glm(z1_bi~fit_o2snp$Tt, family = 'binomial')
sumy_bi_o2snp <-  lmfit_o2snp %>% summary
prob=predict(lmfit_o2snp,type=c("response"))
auc_o2snp <- roc(z1_bi ~ prob)$auc
print(sumy_bi_o2snp)

lmfit_p <- glm(z1_bi~t_p, family = 'binomial')
sumy_bi_p <-  lmfit_p %>% summary
prob=predict(lmfit_p,type=c("response"))
auc_p <- roc(z1_bi ~ prob)$auc
print(sumy_bi_p)

lmfit_pex <- glm(z1_bi~t_pex, family = 'binomial')
sumy_bi_pex <-  lmfit_pex %>% summary
prob=predict(lmfit_pex,type=c("response"))
auc_pex <- roc(z1_bi ~ prob)$auc
print(sumy_bi_pex)

lmfit_prs <- glm(z1_bi~prs_pc, family = 'binomial')
sumy_bi_prs <-  lmfit_prs %>% summary
prob=predict(lmfit_prs,type=c("response"))
auc_prs <- roc(z1_bi ~ prob)$auc
print(sumy_bi_prs)

lmfit_prsZ <- glm(z1_bi~prsZ, family = 'binomial')
sumy_bi_prsZ <-  lmfit_prsZ %>% summary
prob=predict(lmfit_prsZ,type=c("response"))
auc_prsZ <- roc(z1_bi ~ prob)$auc
print(sumy_bi_prsZ)
#######################################################################
# performance in test

# O2PLS
t_test_o2 <- gene_t %*% fit_o2$W.
print('O2PLS: correlation of T with True in test')
print('cor with T_q')
cor(T_q_t, t_test_o2)
print('cor with PCA(y)')
cor(prcomp(y_nonoise)$x[-(1:2000),1:5], t_test_o2)
pred_o2 <- t_test_o2 %*% sumy_o2$coefficients[-1, 1]
sumy_o2_test <- lm(z1_t~pred_o2) %>% summary
sumy_o2_test %>% print

# O2PLS SNP
t_test_o2snp <- x_t %*% fit_o2snp$W.
print('O2PLS SNP: correlation of T with True in test')
print('cor with T_q')
cor(T_q_t, t_test_o2snp)
print('cor with PCA(y)')
cor(prcomp(y_nonoise)$x[-(1:2000),1:5], t_test_o2snp)
pred_o2snp <- t_test_o2snp %*% sumy_o2snp$coefficients[-1, 1]
sumy_o2snp_test <- lm(z1_t~pred_o2snp) %>% summary
sumy_o2snp_test %>% print

# PO2PLS
t_test_p <- with(fit_p$parameters, (gene_t - gene_t%*%Wo%*%t(Wo)) %*% W)
print('PO2PLS: correlation of T with True in test')
print('cor with T_q')
cor(T_q_t, t_test_p)
print('cor with PCA(y)')
cor(prcomp(y_nonoise)$x[-(1:2000),1:5], t_test_p)
pred_p <- t_test_p %*% sumy_p$coefficients[-1, 1]
sumy_p_test <- lm(z1_t~pred_p) %>% summary
sumy_p_test %>% print

# PO2PLS
t_test_pex <- with(fit_pex$parameters, (gene_t - gene_t%*%Wo%*%t(Wo)) %*% W)
print('PO2PLS: correlation of T with True in test')
print('cor with T_q')
cor(T_q_t, t_test_pex)
print('cor with PCA(y)')
cor(prcomp(y_nonoise)$x[-(1:2000),1:5], t_test_pex)
pred_pex <- t_test_pex %*% sumy_pex$coefficients[-1, 1]
sumy_pex_test <- lm(z1_t~pred_pex) %>% summary
sumy_pex_test %>% print

# PRS
prs_test <- matrix(NA, 1465, 23)
for(yi in 1:23){
  prs_temp <- read.table(paste('./fit_files/PRS_y', yi, name_suf, '_test.all_score', sep = ''), header = T)
  prs_temp <- prs_temp[match(rownames(gene_t),prs_temp$IID), ]
  if(all.equal(prs_temp$IID, rownames(gene_t))!=T) stop('prs order mismatch')
  prs_test[,yi] <- prs_temp[,3]
}
rownames(prs_test) <- rownames(gene_t)
# ggcorrplot::ggcorrplot(cor(prs))

# PCA of 23 PRS
prs_pc_t <- prs_test%*%prs_pca$rotation[,1:5]
# prs_pca_t <- prcomp(prs_test)
# crossprod(prs_pca$rotation[,1:5],prs_pca_t$rotation[,1:5] )
# prs_pc_t <- prs_pca_t$x[,1:5]
print('PRS: correlation of PRS with True in test')
print('cor with T_q')
cor(T_q_t, prs_pc_t)
print('cor with PCA(y)')
cor(prcomp(y_nonoise)$x[-(1:2000),1:5], prs_pc_t)
pred_prs <- prs_pc_t%*%sumy_prs$coefficients[-1, 1]
sumy_prs_t <- lm(z1_t~pred_prs) %>% summary
print(sumy_prs_t)

# PRS Z
prsZ_t <- read.table(paste('./fit_files/PRS_z1',name_suf, '_test.all_score', sep = ''), header = T)
prsZ_t <- prsZ_t[match(rownames(gene_t),prsZ_t$IID), ]
if(all.equal(prsZ_t$IID, rownames(gene_t))!=T) stop('prsZ_t order mismatch')
pred_prsZ <- prsZ_t[,3] %>% t %>% t
rownames(pred_prsZ) <- rownames(gene_t)
# ggcorrplot::ggcorrplot(cor(prs))
# PCA of 23 PRS
sumy_prsZ_t <- lm(z1_t~pred_prsZ) %>% summary
print(sumy_prsZ_t)


####################
# Binary
pred_bi_o2 <- t_test_o2 %*% sumy_bi_o2$coefficients[-1, 1]
lmfit_o2_t <- glm(z1_bi_t~pred_bi_o2, family = 'binomial')
lmfit_o2_t %>% summary
PseudoR2(lmfit_o2_t,'Nagelkerke')
prob=predict(lmfit_o2_t,type=c("response"))
# print('AUC of O2PLS in test')
auc_o2_t <- roc(z1_bi_t ~ prob)$auc

pred_bi_o2snp <- t_test_o2snp %*% sumy_bi_o2snp$coefficients[-1, 1]
lmfit_o2snp_t <- glm(z1_bi_t~pred_bi_o2snp, family = 'binomial')
lmfit_o2snp_t %>% summary
PseudoR2(lmfit_o2snp_t,'Nagelkerke')
prob=predict(lmfit_o2snp_t,type=c("response"))
# print('AUC of o2snpPLS in test')
auc_o2snp_t <- roc(z1_bi_t ~ prob)$auc

pred_bi_p <- t_test_p %*% sumy_bi_p$coefficients[-1, 1]
lmfit_p_t <- glm(z1_bi_t~pred_bi_p, family = 'binomial')
lmfit_p_t %>% summary
PseudoR2(lmfit_p_t,'Nagelkerke')
prob=predict(lmfit_p_t,type=c("response"))
# print('AUC of pPLS in test')
auc_p_t <- roc(z1_bi_t ~ prob)$auc

pred_bi_pex <- t_test_pex %*% sumy_bi_pex$coefficients[-1, 1]
lmfit_pex_t <- glm(z1_bi_t~pred_bi_pex, family = 'binomial')
lmfit_pex_t %>% summary
PseudoR2(lmfit_pex_t,'Nagelkerke')
prob=predict(lmfit_pex_t,type=c("response"))
# print('AUC of pPLS in test')
auc_pex_t <- roc(z1_bi_t ~ prob)$auc

pred_bi_prs <- prs_pc_t %*% sumy_bi_prs$coefficients[-1, 1]
lmfit_prs_t <- glm(z1_bi_t~pred_bi_prs, family = 'binomial')
lmfit_prs_t %>% summary
PseudoR2(lmfit_prs_t,'Nagelkerke')
prob=predict(lmfit_prs_t,type=c("response"))
print('AUC of PRS in test')
auc_prs_t <- roc(z1_bi_t ~ prob)$auc

lmfit_prsZ_t <- glm(z1_bi_t~pred_prsZ, family = 'binomial')
lmfit_prsZ_t %>% summary
PseudoR2(lmfit_prsZ_t,'Nagelkerke')
prob=predict(lmfit_prsZ_t,type=c("response"))
print('AUC of prsZ in test')
auc_prsZ_t <- roc(z1_bi_t ~ prob)$auc

results <- list(R2_o2 = sumy_o2$adj.r.squared,
                R2_o2snp = sumy_o2snp$adj.r.squared,
                R2_p = sumy_p$adj.r.squared,
                R2_pex = sumy_pex$adj.r.squared,
                R2_prs = sumy_prs$adj.r.squared,
                R2_prsZ = sumy_prsZ$adj.r.squared,
                R2_o2_t = sumy_o2_test$adj.r.squared,
                R2_o2snp_t = sumy_o2snp_test$adj.r.squared,
                R2_p_t = sumy_p_test$adj.r.squared,
                R2_pex_t = sumy_pex_test$adj.r.squared,
                R2_prs_t = sumy_prs_t$adj.r.squared,
                R2_prsZ_t = sumy_prsZ_t$adj.r.squared,
                # rmsep_o2 = rmsep(sumy_o2),
                # rmsep_o2snp = rmsep(sumy_o2snp),
                # rmsep_p = rmsep(sumy_p),
                # rmsep_pex = rmsep(sumy_pex),
                # rmsep_prs = rmsep(sumy_prs),
                # rmsep_prsZ = rmsep(sumy_prsZ),
                # rmsep_o2_t = rmsep(sumy_o2_test),
                # rmsep_o2snp_t = rmsep(sumy_o2snp_test),
                # rmsep_p_t = rmsep(sumy_p_test),
                # rmsep_pex_t = rmsep(sumy_pex_test),
                # rmsep_prs_t = rmsep(sumy_prs_t),
                # rmsep_prsZ_t = rmsep(sumy_prsZ_t),
                auc_o2=as.numeric(auc_o2),
                auc_o2snp=as.numeric(auc_o2snp),
                auc_p=as.numeric(auc_p),
                auc_pex=as.numeric(auc_pex),
                auc_prs=as.numeric(auc_prs),
                auc_prsZ=as.numeric(auc_prsZ),
                auc_o2_t=as.numeric(auc_o2_t),
                auc_o2snp_t=as.numeric(auc_o2snp_t),
                auc_p_t=as.numeric(auc_p_t),
                auc_pex_t=as.numeric(auc_pex_t),
                auc_prs_t=as.numeric(auc_prs_t),
                auc_prsZ_t=as.numeric(auc_prsZ_t),
                pval_o2=coefficients(summary(lmfit_o2_t))[2,4],
                pval_o2snp=coefficients(summary(lmfit_o2snp_t))[2,4],
                pval_p=coefficients(summary(lmfit_p_t))[2,4],
                pval_pex=coefficients(summary(lmfit_pex_t))[2,4],
                pval_prs=coefficients(summary(lmfit_prs_t))[2,4],
                pval_prsZ=coefficients(summary(lmfit_prsZ_t))[2,4])
print(results)

saveRDS(results, file = paste('./results/outpsnpz1', name_suf, '.rds', sep = ''))

#############################################################################
# Z2
# performance in training

# O2PLS
fit_o2 <- readRDS(file=paste('./fit_files/fit_o2', name_suf, '.rds', sep = ''))
print('O2PLS: correlation of T with True')
print('cor with T_q')
cor(T_q, fit_o2$Tt)
print('cor with PCA(y)')
cor(prcomp(y_nonoise)$x[1:2000,1:5], fit_o2$Tt)
sumy_o2 <- summary(lm(z2~fit_o2$Tt))
print(sumy_o2)


# O2PLS
fit_o2snp <- readRDS(file=paste('./fit_files/fit_o2snp', name_suf, '.rds', sep = ''))
print('O2PLS SNP: correlation of T with True')
print('cor with T_q')
cor(T_q, fit_o2snp$Tt)
print('cor with PCA(y)')
cor(prcomp(y_nonoise)$x[1:2000,1:5], fit_o2snp$Tt)
sumy_o2snp <- lm(z2~fit_o2snp$Tt) %>% summary
print(sumy_o2snp)


# PO2PLS
fit_p <- readRDS(file=paste('./fit_files/fit_p', name_suf, '.rds', sep = ''))
print('PO2PLS: correlation of T with True')
t_p <- with(fit_p$parameters, (gene - gene%*%Wo%*%t(Wo)) %*% W)
print('cor with T_q')
cor(T_q, t_p)
print('cor with PCA(y)')
cor(prcomp(y_nonoise)$x[1:2000,1:5], t_p)
sumy_p <- lm(z2~t_p) %>% summary
print(sumy_p)

# PO2PLS 10 X-specific
fit_pex <- readRDS(file=paste('./fit_files/fit_pex15', name_suf, '.rds', sep = ''))
print('PO2PLS: correlation of T with True')
t_pex <- with(fit_pex$parameters, (gene - gene%*%Wo%*%t(Wo)) %*% W)
print('cor with T_q')
cor(T_q, t_pex)
print('cor with PCA(y)')
cor(prcomp(y_nonoise)$x[1:2000,1:5], t_pex)
sumy_pex <- lm(z2~t_pex) %>% summary
print(sumy_pex)

# PRS Y
prs <- matrix(NA, 2000, 23)
for(yi in 1:23){
  prs_temp <- read.table(paste('./fit_files/PRS_y', yi, name_suf, '.best', sep = ''), header = T)
  prs_temp <- prs_temp[match(rownames(gene),prs_temp$IID), ]
  if(all.equal(prs_temp$IID, rownames(gene))!=T) stop('prs order mismatch')
  prs[,yi] <- prs_temp$PRS
}
rownames(prs) <- rownames(gene)
# ggcorrplot::ggcorrplot(cor(prs))
# PCA of 23 PRS
prs_pca <- prcomp(prs)
prs_pc <- prs_pca$x[,1:5]
print('PRS: correlation of PRS with True')
print('cor with T_q')
cor(T_q, prs_pc)
print('cor with PCA(y)')
cor(prcomp(y_nonoise)$x[1:2000,1:5], prs_pc)
sumy_prs <- lm(z2~prs_pc) %>% summary
print(sumy_prs)

# PRS Z
prsZ <- read.table(paste('./fit_files/PRS_z2',name_suf, '.best', sep = ''), header = T)
prsZ <- prsZ[match(rownames(gene),prsZ$IID), ]
if(all.equal(prsZ$IID, rownames(gene))!=T) stop('prsZ order mismatch')
prsZ <- prsZ$PRS %>% t %>% t
rownames(prsZ) <- rownames(gene)
# ggcorrplot::ggcorrplot(cor(prs))
# PCA of 23 PRS
sumy_prsZ <- lm(z2~prsZ) %>% summary
print(sumy_prsZ)

##################################
# binary
lmfit_o2 <- glm(z2_bi~fit_o2$Tt, family = 'binomial')
sumy_bi_o2 <- lmfit_o2 %>% summary
prob=predict(lmfit_o2,type=c("response"))
# print('AUC of O2PLS in test')
auc_o2 <- roc(z2_bi ~ prob)$auc
print(sumy_bi_o2)

lmfit_o2snp <- glm(z2_bi~fit_o2snp$Tt, family = 'binomial')
sumy_bi_o2snp <-  lmfit_o2snp %>% summary
prob=predict(lmfit_o2snp,type=c("response"))
auc_o2snp <- roc(z2_bi ~ prob)$auc
print(sumy_bi_o2snp)

lmfit_p <- glm(z2_bi~t_p, family = 'binomial')
sumy_bi_p <-  lmfit_p %>% summary
prob=predict(lmfit_p,type=c("response"))
auc_p <- roc(z2_bi ~ prob)$auc
print(sumy_bi_p)

lmfit_pex <- glm(z2_bi~t_pex, family = 'binomial')
sumy_bi_pex <-  lmfit_pex %>% summary
prob=predict(lmfit_pex,type=c("response"))
auc_pex <- roc(z2_bi ~ prob)$auc
print(sumy_bi_pex)

lmfit_prs <- glm(z2_bi~prs_pc, family = 'binomial')
sumy_bi_prs <-  lmfit_prs %>% summary
prob=predict(lmfit_prs,type=c("response"))
auc_prs <- roc(z2_bi ~ prob)$auc
print(sumy_bi_prs)

lmfit_prsZ <- glm(z2_bi~prsZ, family = 'binomial')
sumy_bi_prsZ <-  lmfit_prsZ %>% summary
prob=predict(lmfit_prsZ,type=c("response"))
auc_prsZ <- roc(z2_bi ~ prob)$auc
print(sumy_bi_prsZ)
#######################################################################
# performance in test

# O2PLS
t_test_o2 <- gene_t %*% fit_o2$W.
print('O2PLS: correlation of T with True in test')
print('cor with T_q')
cor(T_q_t, t_test_o2)
print('cor with PCA(y)')
cor(prcomp(y_nonoise)$x[-(1:2000),1:5], t_test_o2)
pred_o2 <- t_test_o2 %*% sumy_o2$coefficients[-1, 1]
sumy_o2_test <- lm(z2_t~pred_o2) %>% summary
sumy_o2_test %>% print

# O2PLS SNP
t_test_o2snp <- x_t %*% fit_o2snp$W.
print('O2PLS SNP: correlation of T with True in test')
print('cor with T_q')
cor(T_q_t, t_test_o2snp)
print('cor with PCA(y)')
cor(prcomp(y_nonoise)$x[-(1:2000),1:5], t_test_o2snp)
pred_o2snp <- t_test_o2snp %*% sumy_o2snp$coefficients[-1, 1]
sumy_o2snp_test <- lm(z2_t~pred_o2snp) %>% summary
sumy_o2snp_test %>% print

# PO2PLS
t_test_p <- with(fit_p$parameters, (gene_t - gene_t%*%Wo%*%t(Wo)) %*% W)
print('PO2PLS: correlation of T with True in test')
print('cor with T_q')
cor(T_q_t, t_test_p)
print('cor with PCA(y)')
cor(prcomp(y_nonoise)$x[-(1:2000),1:5], t_test_p)
pred_p <- t_test_p %*% sumy_p$coefficients[-1, 1]
sumy_p_test <- lm(z2_t~pred_p) %>% summary
sumy_p_test %>% print

# PO2PLS
t_test_pex <- with(fit_pex$parameters, (gene_t - gene_t%*%Wo%*%t(Wo)) %*% W)
print('PO2PLS: correlation of T with True in test')
print('cor with T_q')
cor(T_q_t, t_test_pex)
print('cor with PCA(y)')
cor(prcomp(y_nonoise)$x[-(1:2000),1:5], t_test_pex)
pred_pex <- t_test_pex %*% sumy_pex$coefficients[-1, 1]
sumy_pex_test <- lm(z2_t~pred_pex) %>% summary
sumy_pex_test %>% print

# PRS
prs_test <- matrix(NA, 1465, 23)
for(yi in 1:23){
  prs_temp <- read.table(paste('./fit_files/PRS_y', yi, name_suf, '_test.all_score', sep = ''), header = T)
  prs_temp <- prs_temp[match(rownames(gene_t),prs_temp$IID), ]
  if(all.equal(prs_temp$IID, rownames(gene_t))!=T) stop('prs order mismatch')
  prs_test[,yi] <- prs_temp[,3]
}
rownames(prs_test) <- rownames(gene_t)
# ggcorrplot::ggcorrplot(cor(prs))

# PCA of 23 PRS
prs_pc_t <- prs_test%*%prs_pca$rotation[,1:5]
# prs_pca_t <- prcomp(prs_test)
# crossprod(prs_pca$rotation[,1:5],prs_pca_t$rotation[,1:5] )
# prs_pc_t <- prs_pca_t$x[,1:5]
print('PRS: correlation of PRS with True in test')
print('cor with T_q')
cor(T_q_t, prs_pc_t)
print('cor with PCA(y)')
cor(prcomp(y_nonoise)$x[-(1:2000),1:5], prs_pc_t)
pred_prs <- prs_pc_t%*%sumy_prs$coefficients[-1, 1]
sumy_prs_t <- lm(z2_t~pred_prs) %>% summary
print(sumy_prs_t)

# PRS Z
prsZ_t <- read.table(paste('./fit_files/PRS_z2',name_suf, '_test.all_score', sep = ''), header = T)
prsZ_t <- prsZ_t[match(rownames(gene_t),prsZ_t$IID), ]
if(all.equal(prsZ_t$IID, rownames(gene_t))!=T) stop('prsZ_t order mismatch')
pred_prsZ <- prsZ_t[,3] %>% t %>% t
rownames(pred_prsZ) <- rownames(gene_t)
# ggcorrplot::ggcorrplot(cor(prs))
# PCA of 23 PRS
sumy_prsZ_t <- lm(z2_t~pred_prsZ) %>% summary
print(sumy_prsZ_t)


####################
# Binary
pred_bi_o2 <- t_test_o2 %*% sumy_bi_o2$coefficients[-1, 1]
lmfit_o2_t <- glm(z2_bi_t~pred_bi_o2, family = 'binomial')
lmfit_o2_t %>% summary
PseudoR2(lmfit_o2_t,'Nagelkerke')
prob=predict(lmfit_o2_t,type=c("response"))
# print('AUC of O2PLS in test')
auc_o2_t <- roc(z2_bi_t ~ prob)$auc

pred_bi_o2snp <- t_test_o2snp %*% sumy_bi_o2snp$coefficients[-1, 1]
lmfit_o2snp_t <- glm(z2_bi_t~pred_bi_o2snp, family = 'binomial')
lmfit_o2snp_t %>% summary
PseudoR2(lmfit_o2snp_t,'Nagelkerke')
prob=predict(lmfit_o2snp_t,type=c("response"))
# print('AUC of o2snpPLS in test')
auc_o2snp_t <- roc(z2_bi_t ~ prob)$auc

pred_bi_p <- t_test_p %*% sumy_bi_p$coefficients[-1, 1]
lmfit_p_t <- glm(z2_bi_t~pred_bi_p, family = 'binomial')
lmfit_p_t %>% summary
PseudoR2(lmfit_p_t,'Nagelkerke')
prob=predict(lmfit_p_t,type=c("response"))
# print('AUC of pPLS in test')
auc_p_t <- roc(z2_bi_t ~ prob)$auc

pred_bi_pex <- t_test_pex %*% sumy_bi_pex$coefficients[-1, 1]
lmfit_pex_t <- glm(z2_bi_t~pred_bi_pex, family = 'binomial')
lmfit_pex_t %>% summary
PseudoR2(lmfit_pex_t,'Nagelkerke')
prob=predict(lmfit_pex_t,type=c("response"))
# print('AUC of pPLS in test')
auc_pex_t <- roc(z2_bi_t ~ prob)$auc

pred_bi_prs <- prs_pc_t %*% sumy_bi_prs$coefficients[-1, 1]
lmfit_prs_t <- glm(z2_bi_t~pred_bi_prs, family = 'binomial')
lmfit_prs_t %>% summary
PseudoR2(lmfit_prs_t,'Nagelkerke')
prob=predict(lmfit_prs_t,type=c("response"))
print('AUC of PRS in test')
auc_prs_t <- roc(z2_bi_t ~ prob)$auc

lmfit_prsZ_t <- glm(z2_bi_t~pred_prsZ, family = 'binomial')
lmfit_prsZ_t %>% summary
PseudoR2(lmfit_prsZ_t,'Nagelkerke')
prob=predict(lmfit_prsZ_t,type=c("response"))
print('AUC of prsZ in test')
auc_prsZ_t <- roc(z2_bi_t ~ prob)$auc

results <- list(R2_o2 = sumy_o2$adj.r.squared,
                R2_o2snp = sumy_o2snp$adj.r.squared,
                R2_p = sumy_p$adj.r.squared,
                R2_pex = sumy_pex$adj.r.squared,
                R2_prs = sumy_prs$adj.r.squared,
                R2_prsZ = sumy_prsZ$adj.r.squared,
                R2_o2_t = sumy_o2_test$adj.r.squared,
                R2_o2snp_t = sumy_o2snp_test$adj.r.squared,
                R2_p_t = sumy_p_test$adj.r.squared,
                R2_pex_t = sumy_pex_test$adj.r.squared,
                R2_prs_t = sumy_prs_t$adj.r.squared,
                R2_prsZ_t = sumy_prsZ_t$adj.r.squared,
                # rmsep_o2 = rmsep(sumy_o2),
                # rmsep_o2snp = rmsep(sumy_o2snp),
                # rmsep_p = rmsep(sumy_p),
                # rmsep_pex = rmsep(sumy_pex),
                # rmsep_prs = rmsep(sumy_prs),
                # rmsep_prsZ = rmsep(sumy_prsZ),
                # rmsep_o2_t = rmsep(sumy_o2_test),
                # rmsep_o2snp_t = rmsep(sumy_o2snp_test),
                # rmsep_p_t = rmsep(sumy_p_test),
                # rmsep_pex_t = rmsep(sumy_pex_test),
                # rmsep_prs_t = rmsep(sumy_prs_t),
                # rmsep_prsZ_t = rmsep(sumy_prsZ_t),
                auc_o2=as.numeric(auc_o2),
                auc_o2snp=as.numeric(auc_o2snp),
                auc_p=as.numeric(auc_p),
                auc_pex=as.numeric(auc_pex),
                auc_prs=as.numeric(auc_prs),
                auc_prsZ=as.numeric(auc_prsZ),
                auc_o2_t=as.numeric(auc_o2_t),
                auc_o2snp_t=as.numeric(auc_o2snp_t),
                auc_p_t=as.numeric(auc_p_t),
                auc_pex_t=as.numeric(auc_pex_t),
                auc_prs_t=as.numeric(auc_prs_t),
                auc_prsZ_t=as.numeric(auc_prsZ_t),
                pval_o2=coefficients(summary(lmfit_o2_t))[2,4],
                pval_o2snp=coefficients(summary(lmfit_o2snp_t))[2,4],
                pval_p=coefficients(summary(lmfit_p_t))[2,4],
                pval_pex=coefficients(summary(lmfit_pex_t))[2,4],
                pval_prs=coefficients(summary(lmfit_prs_t))[2,4],
                pval_prsZ=coefficients(summary(lmfit_prsZ_t))[2,4])
print(results)

saveRDS(results, file = paste('./results/outpsnpz2', name_suf, '.rds', sep = ''))

print('End successfully')