arrID <- as.numeric(Sys.getenv('SLURM_ARRAY_TASK_ID'))
set.seed(arrID)

# suffix of file name generated by this file
name_suf_y <- paste0('_6_0.001_0.5_',arrID)
name_suf_yy <- paste0('_simu2_', arrID)

library(dplyr)
library(magrittr)
library(data.table)
library(OmicsPLS)
library(DescTools)
library(ggplot2)
library(pROC)
library(PO2PLS)
library(GenABEL)
# library(MultiABEL)
# library(lassosum)

#######################################################################
# load X
# x <- readRDS(paste('./dat_rep/dat_training_',arrID,'.rds', sep = ''))
x_t <- readRDS(paste('./dat_rep/dat_test_',arrID,'.rds', sep = ''))
# dim(x); dim(x_t)

# For PO2PLS
gene <- readRDS(paste('./dat_rep/GeneData_training_',arrID,'.rds', sep = ''))
# gene %>% dim
gene_t <- readRDS(paste('./dat_rep/GeneData_test_',arrID,'.rds', sep = ''))

PCA_weight <- readRDS(paste('./dat_rep/PCAweight_',arrID,'.rds', sep = ''))

load(file=paste('./fit_dat_simu2/dat_yz', name_suf_yy, '.RData', sep = ''))

#######################################################################
## Prediction
#######################################################################
# performance in training

# O2PLS
fit_o2 <- readRDS(file=paste0('./fit_files/fit_o2', name_suf_y, '.rds'))
fit_o2_yy <- readRDS(file=paste0('./fit_files_simu2/fit_o2', name_suf_yy, '.rds'))
sumy_o2 <- summary(lm(z~fit_o2$Tt+fit_o2_yy$Tt))
print(sumy_o2)


# O2PLS snp
fit_o2snp <- readRDS(file=paste0('./fit_files/fit_o2snp', name_suf_y, '.rds'))
fit_o2snp_yy <- readRDS(file=paste0('./fit_files_simu2/fit_o2snp', name_suf_yy, '.rds'))
sumy_o2snp <- summary(lm(z~fit_o2snp$Tt+fit_o2snp_yy$Tt))
print(sumy_o2snp)


# PO2PLS
fit_pex <- readRDS(file=paste0('./fit_files/fit_pex15', name_suf_y, '.rds'))
fit_pex_yy <- readRDS(file=paste0('./fit_files_simu2/fit_pex', name_suf_yy, '.rds'))
t_pex <- with(fit_pex$parameters, (gene - gene%*%Wo%*%t(Wo)) %*% W)
t_pex_yy <- with(fit_pex_yy$parameters, (gene - gene%*%Wo%*%t(Wo)) %*% W)
sumy_pex <- lm(z~t_pex+t_pex_yy) %>% summary
print(sumy_pex)


# PRS Y
prs <- matrix(NA, 2000, 23)
for(yi in 1:23){
  prs_temp <- read.table(paste0('./fit_files/PRS_y', yi, name_suf_y, '.best'), header = T)
  prs_temp <- prs_temp[match(rownames(gene),prs_temp$IID), ]
  if(all.equal(prs_temp$IID, rownames(gene))!=T) stop('prs order mismatch')
  prs[,yi] <- prs_temp$PRS
}
rownames(prs) <- rownames(gene)
# ggcorrplot::ggcorrplot(cor(prs))
# PCA of 23 PRS
prs_pca <- prcomp(prs)
prs_pc <- prs_pca$x[,1:5]

# PRS YY
prs_yy <- matrix(NA, 2000, 10)
for(yi in 1:10){
  prs_yy_temp <- read.table(paste0('./fit_files_simu2/PRS_yy', yi, name_suf_yy, '.best'), header = T)
  prs_yy_temp <- prs_yy_temp[match(rownames(gene),prs_yy_temp$IID), ]
  if(all.equal(prs_yy_temp$IID, rownames(gene))!=T) stop('prs_yy order mismatch')
  prs_yy[,yi] <- prs_yy_temp$PRS
}
rownames(prs_yy) <- rownames(gene)
# ggcorrplot::ggcorrplot(cor(prs_yy))
# PCA of 23 PRS
prs_yy_pca <- prcomp(prs_yy)
prs_yy_pc <- prs_yy_pca$x[,1:4]

sumy_prs <- lm(z~prs_pc + prs_yy_pc) %>% summary
print(sumy_prs)


# PRS Z
prsZ <- read.table(paste0('./fit_files_simu2/PRS_z', name_suf_yy, '.best'), header = T)
prsZ <- prsZ[match(rownames(gene),prsZ$IID), ]
if(all.equal(prsZ$IID, rownames(gene))!=T) stop('prsZ order mismatch')
prsZ <- prsZ$PRS %>% t %>% t
rownames(prsZ) <- rownames(gene)
sumy_prsZ <- lm(z~prsZ) %>% summary
print(sumy_prsZ)

########################################################
# performance in test

# O2PLS
t_test_o2 <- gene_t %*% fit_o2$W.
t_test_o2_yy <- gene_t %*% fit_o2_yy$W.

pred_o2 <- cbind(t_test_o2,t_test_o2_yy) %*% sumy_o2$coefficients[-1, 1]
sumy_o2_test <- lm(z_t~pred_o2) %>% summary
sumy_o2_test %>% print


# O2PLS SNP
t_test_o2snp <- x_t %*% fit_o2snp$W.
t_test_o2snp_yy <- x_t %*% fit_o2snp_yy$W.

pred_o2snp <- cbind(t_test_o2snp,t_test_o2snp_yy) %*% sumy_o2snp$coefficients[-1, 1]
sumy_o2snp_test <- lm(z_t~pred_o2snp) %>% summary
sumy_o2snp_test %>% print


# PO2PLS
t_test_pex <- with(fit_pex$parameters, (gene_t - gene_t%*%Wo%*%t(Wo)) %*% W)
t_test_pex_yy <- with(fit_pex_yy$parameters, (gene_t - gene_t%*%Wo%*%t(Wo)) %*% W)

pred_pex <- cbind(t_test_pex, t_test_pex_yy) %*% sumy_pex$coefficients[-1, 1]
sumy_pex_test <- lm(z_t~pred_pex) %>% summary
sumy_pex_test %>% print


# PRS Y
prs_test <- matrix(NA, 1465, 23)
for(yi in 1:23){
  prs_temp <- read.table(paste0('./fit_files/PRS_y', yi, name_suf_y, '_test.all_score'), header = T)
  prs_temp <- prs_temp[match(rownames(gene_t),prs_temp$IID), ]
  if(all.equal(prs_temp$IID, rownames(gene_t))!=T) stop('prs order mismatch')
  prs_test[,yi] <- prs_temp[,3]
}
rownames(prs_test) <- rownames(gene_t)
# PCA of 23 PRS
prs_pc_t <- prs_test%*%prs_pca$rotation[,1:5]

# PRS YY
prs_yy_test <- matrix(NA, 1465, 10)
for(yi in 1:10){
  prs_yy_temp <- read.table(paste0('./fit_files_simu2/PRS_yy', yi, name_suf_yy, '_test.all_score'), header = T)
  prs_yy_temp <- prs_yy_temp[match(rownames(gene_t),prs_yy_temp$IID), ]
  if(all.equal(prs_yy_temp$IID, rownames(gene_t))!=T) stop('prs_yy order mismatch')
  prs_yy_test[,yi] <- prs_yy_temp[,3]
}
rownames(prs_yy_test) <- rownames(gene_t)
# PCA of 10 PRS
prs_yy_pc_t <- prs_yy_test%*%prs_yy_pca$rotation[,1:4]

pred_prs <- cbind(prs_pc_t, prs_yy_pc_t) %*% sumy_prs$coefficients[-1, 1]
sumy_prs_t <- lm(z_t~pred_prs) %>% summary
print(sumy_prs_t)

# PRS Z
prsZ_t <- read.table(paste0('./fit_files_simu2/PRS_z',name_suf_yy, '_test.all_score'), header = T)
prsZ_t <- prsZ_t[match(rownames(gene_t),prsZ_t$IID), ]
if(all.equal(prsZ_t$IID, rownames(gene_t))!=T) stop('prsZ_t order mismatch')
pred_prsZ <- prsZ_t[,3] %>% t %>% t
rownames(pred_prsZ) <- rownames(gene_t)
# ggcorrplot::ggcorrplot(cor(prs))
# PCA of 23 PRS
sumy_prsZ_t <- lm(z_t~pred_prsZ) %>% summary
print(sumy_prsZ_t)

#######################################################################
## TPR
#######################################################################
# map SNPs to genes
snp_gene <- sapply(PCA_weight, rownames)
snp_gene_map <- data.frame(SNP=unlist(snp_gene, use.names=F), Gene=rep(names(snp_gene), lengths(snp_gene)))

# Get true relevant genes
w <- readRDS('w_cut_gene.rds')
w <- w$`0.001`

y_gene <- lapply(6:10, function(j) rownames(w)[w[,j]!=0]) %>% unlist
y_gene <- sapply(y_gene, function(e) strsplit(e, '_')[[1]][1]) %>% unique

yy_gene <- lapply(11:14, function(j) rownames(w)[w[,j]!=0]) %>% unlist
yy_gene <- sapply(yy_gene, function(e) strsplit(e, '_')[[1]][1]) %>% unique

# overlap
common_gene <- y_gene[y_gene %in% yy_gene]
y_only_gene <- y_gene[!y_gene %in% common_gene]
yy_only_gene <- yy_gene[!yy_gene %in% common_gene]

top_n=40

# PRS
# load PRS SNPs per y
snp_l <- lapply(1:23, function(yi){
  snps <- read.table(paste0('./fit_files/PRS_y',yi,name_suf_y,'_test.snp'), header = T)
  snps <- merge(snps, snp_gene_map)
})
prs_y_gene <- do.call(rbind, snp_l) %>% arrange(P)
prs_y_gene <- prs_y_gene$Gene %>% unique
prs_y_gene <- prs_y_gene[1:top_n]
# prs_y_gene_nr <- length(prs_y_gene)
prs_y_in_common <- sum(prs_y_gene %in% common_gene)
prs_y_in_y <- sum(prs_y_gene %in% y_only_gene)
prs_y_in_yy <- sum(prs_y_gene %in% yy_only_gene)


snp_l <- lapply(1:10, function(yi){
  snps <- read.table(paste0('./fit_files_simu2/PRS_yy',yi,name_suf_yy,'_test.snp'), header = T)
  snps <- merge(snps, snp_gene_map)
})
prs_yy_gene <- do.call(rbind, snp_l) %>% arrange(P)
prs_yy_gene <- prs_yy_gene$Gene %>% unique
prs_yy_gene <- prs_yy_gene[1:top_n]
# prs_yy_gene_nr <- length(prs_yy_gene)
prs_yy_in_common <- sum(prs_yy_gene %in% common_gene)
prs_yy_in_y <- sum(prs_yy_gene %in% y_only_gene)
prs_yy_in_yy <- sum(prs_yy_gene %in% yy_only_gene)

# snp_l <- lapply(1:10, function(yi){
#   snps <- read.table(paste0('./fit_files_simu2/PRS_yy',yi,name_suf_yy,'_test.snp'), header = T)
#   snps <- merge(snps, snp_gene_map)
# })
# prs_yy_gene <- do.call(rbind, snp_l)$Gene %>% unique
# prs_yy_gene_nr <- length(prs_yy_gene)
# prs_yy_in_common <- sum(prs_yy_gene %in% common_gene)
# prs_yy_in_y <- sum(prs_yy_gene %in% y_only_gene)
# prs_yy_in_yy <- sum(prs_yy_gene %in% yy_only_gene)


# PRS-Z
snps <- read.table(paste0('./fit_files_simu2/PRS_z',name_suf_yy,'_test.snp'), header = T)
snps <- merge(snps, snp_gene_map)

prs_z_gene <- snps$Gene %>% unique
# prs_z_gene_nr <- length(prs_z_gene)
prs_z_in_common <- sum(prs_z_gene %in% common_gene)
prs_z_in_y <- sum(prs_z_gene %in% y_only_gene)
prs_z_in_yy <- sum(prs_z_gene %in% yy_only_gene)


# O2PLS
W_bind <- fit_o2$W. %>% t %>% as.data.frame %>% unlist
W_bind <- W_bind %>% abs %>% sort(decreasing = T)
o2_y_gene <- sapply(names(W_bind)[1:300], function(e) strsplit(e, '_')[[1]][1]) %>% unique
o2_y_gene <- o2_y_gene[1:top_n]
o2_y_in_common <- sum(o2_y_gene %in% common_gene)
o2_y_in_y <- sum(o2_y_gene %in% y_only_gene)
o2_y_in_yy <- sum(o2_y_gene %in% yy_only_gene)

W_bind <- fit_o2_yy$W. %>% t %>% as.data.frame %>% unlist
W_bind <- W_bind %>% abs %>% sort(decreasing = T)
o2_yy_gene <- sapply(names(W_bind)[1:300], function(e) strsplit(e, '_')[[1]][1]) %>% unique
o2_yy_gene <- o2_yy_gene[1:top_n]
o2_yy_in_common <- sum(o2_yy_gene %in% common_gene)
o2_yy_in_y <- sum(o2_yy_gene %in% y_only_gene)
o2_yy_in_yy <- sum(o2_yy_gene %in% yy_only_gene)

# o2_y_gene <- lapply(1:5, function(j) rownames(fit_o2$W.)[order(abs(fit_o2$W.[,j]), decreasing = T)] %>% head(62)) %>% unlist
# o2_y_gene <- sapply(o2_y_gene, function(e) strsplit(e, '_')[[1]][1]) %>% unique
# o2_y_gene_nr <- length(o2_y_gene)
# o2_y_in_common <- sum(o2_y_gene %in% common_gene)
# o2_y_in_y <- sum(o2_y_gene %in% y_only_gene)
# o2_y_in_yy <- sum(o2_y_gene %in% yy_only_gene)

# PO2PLS
W_bind <- fit_pex$parameters$W %>% t %>% as.data.frame %>% unlist
W_bind <- W_bind %>% abs %>% sort(decreasing = T)
p_y_gene <- sapply(names(W_bind)[1:300], function(e) strsplit(e, '_')[[1]][1]) %>% unique
p_y_gene <- p_y_gene[1:top_n]
p_y_in_common <- sum(p_y_gene %in% common_gene)
p_y_in_y <- sum(p_y_gene %in% y_only_gene)
p_y_in_yy <- sum(p_y_gene %in% yy_only_gene)

W_bind <- fit_pex_yy$parameters$W %>% t %>% as.data.frame %>% unlist
W_bind <- W_bind %>% abs %>% sort(decreasing = T)
p_yy_gene <- sapply(names(W_bind)[1:300], function(e) strsplit(e, '_')[[1]][1]) %>% unique
p_yy_gene <- p_yy_gene[1:top_n]
p_yy_in_common <- sum(p_yy_gene %in% common_gene)
p_yy_in_y <- sum(p_yy_gene %in% y_only_gene)
p_yy_in_yy <- sum(p_yy_gene %in% yy_only_gene)


results <- list(R2_o2 = sumy_o2$adj.r.squared,
                R2_o2snp = sumy_o2snp$adj.r.squared,
                R2_pex = sumy_pex$adj.r.squared,
                R2_prs = sumy_prs$adj.r.squared,
                R2_prsZ = sumy_prsZ$adj.r.squared,
                R2_o2_t = sumy_o2_test$adj.r.squared,
                R2_o2snp_t = sumy_o2snp_test$adj.r.squared,
                R2_pex_t = sumy_pex_test$adj.r.squared,
                R2_prs_t = sumy_prs_t$adj.r.squared,
                R2_prsZ_t = sumy_prsZ_t$adj.r.squared,
                prs_y_in_common = prs_y_in_common,
                prs_y_in_y = prs_y_in_y,
                prs_y_in_yy = prs_y_in_yy,
                prs_yy_in_common = prs_yy_in_common,
                prs_yy_in_y = prs_yy_in_y,
                prs_yy_in_yy = prs_yy_in_yy,
                prs_z_in_common = prs_z_in_common,
                prs_z_in_y = prs_z_in_y,
                prs_z_in_yy = prs_z_in_yy,
                o2_y_in_common = o2_y_in_common,
                o2_y_in_y = o2_y_in_y,
                o2_y_in_yy = o2_y_in_yy,
                o2_yy_in_common = o2_yy_in_common,
                o2_yy_in_y = o2_yy_in_y,
                o2_yy_in_yy = o2_yy_in_yy,
                p_y_in_common = p_y_in_common,
                p_y_in_y = p_y_in_y,
                p_y_in_yy = p_y_in_yy,
                p_yy_in_common = p_yy_in_common,
                p_yy_in_y = p_yy_in_y,
                p_yy_in_yy = p_yy_in_yy)

print(results)


saveRDS(results, file = paste('./results_simu2/outp', name_suf_yy, '.rds', sep = ''))

print('End successfully')
